### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by trungdq88** [trungdq88/puppet-string#1]
(NOT ordered by priority)

- [x] it works
- [ ] expose RequestSolver & Matcher classes
- [ ] allow customized jest config
- [ ] config dev server port
- [ ] expose native puppeteer browser object
- [ ] make --watch works
- [ ] ES6 (should be the same as in react-scripts)
- [ ] eject?
- [ ] documentation
- [ ] tests
- [ ] demo project
- [ ] more built-in matchers
- [ ] allow settings for server.js
